#!/usr/bin/env bash
# YourLMS — one-click EC2 install (Apache + PHP + MariaDB, XAMPP-style MySQL).
#
# On the server (after unzipping the package):
#   sudo bash install.sh
#
# Optional:
#   YOURLMS_DIR=/var/www/html/nice-lms YOURLMS_BASE_URL=/nice-lms sudo bash install.sh

set -euo pipefail

if [[ "${EUID:-}" -ne 0 ]]; then
  echo "Run as root: sudo bash install.sh" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${YOURLMS_DIR:-/var/www/html/nice-lms}"
BASE_URL="${YOURLMS_BASE_URL:-/nice-lms}"
DB_NAME="${YOURLMS_DB_NAME:-yourlms}"
DB_USER="${YOURLMS_DB_USER:-yourlms}"
DB_PASS="${YOURLMS_DB_PASS:-$(openssl rand -base64 24 2>/dev/null | tr -d '/+=' | head -c 24)}"

log() { echo "==> $*"; }

detect_os() {
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    echo "${ID:-unknown}"
    return
  fi
  echo "unknown"
}

install_packages() {
  local os="$1"
  log "Installing Apache, PHP, and MariaDB (${os})…"

  case "${os}" in
    amzn|amazon)
      dnf install -y httpd mariadb105-server \
        php php-cli php-mysqlnd php-mbstring php-xml php-gd php-zip php-intl \
        rsync curl
      systemctl enable --now httpd mariadb
      APACHE_USER="apache"
      APACHE_SERVICE="httpd"
      ;;
    ubuntu|debian)
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -y
      apt-get install -y apache2 mariadb-server \
        php php-cli php-mysql php-mbstring php-xml php-gd php-zip php-intl \
        libapache2-mod-php rsync curl
      a2enmod rewrite headers 2>/dev/null || true
      systemctl enable --now apache2 mariadb
      APACHE_USER="www-data"
      APACHE_SERVICE="apache2"
      ;;
    *)
      echo "Unsupported OS (${os}). Use Amazon Linux 2023 or Ubuntu." >&2
      exit 1
      ;;
  esac
}

wait_for_mariadb() {
  local i
  for i in $(seq 1 30); do
    if mysql -e "SELECT 1" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  echo "MariaDB did not become ready in time." >&2
  exit 1
}

setup_database() {
  log "Creating database and application user…"
  mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
}

write_config_local() {
  log "Writing config.local.php…"
  cat > "${INSTALL_DIR}/config.local.php" <<PHP
<?php
declare(strict_types=1);

// Auto-generated by install.sh — EC2 / server install
return [
    'base_url' => '${BASE_URL}',
    'db' => [
        'host' => '127.0.0.1',
        'port' => 3306,
        'name' => '${DB_NAME}',
        'user' => '${DB_USER}',
        'pass' => '${DB_PASS}',
        'charset' => 'utf8mb4',
    ],
];
PHP
  chmod 640 "${INSTALL_DIR}/config.local.php"
}

deploy_app() {
  log "Deploying application to ${INSTALL_DIR}…"
  mkdir -p "${INSTALL_DIR}"
  rsync -a --delete \
    --exclude 'install.sh' \
    --exclude 'yourlms-ec2.zip' \
    --exclude 'yourlms-shared-hosting.zip' \
    --exclude '.git/' \
    --exclude 'config.local.php' \
    --exclude 'uploads/*' \
    --exclude 'data/*.sqlite*' \
    --exclude 'import-temp/' \
    --exclude 'deploy/debian-home/data/' \
    "${SCRIPT_DIR}/" "${INSTALL_DIR}/"
  mkdir -p "${INSTALL_DIR}/uploads"
}

fix_permissions() {
  log "Setting permissions…"
  chown -R "${APACHE_USER}:${APACHE_USER}" "${INSTALL_DIR}"
  chmod -R u+rwX,g+rX "${INSTALL_DIR}/uploads"
  if command -v getenforce >/dev/null 2>&1 && [[ "$(getenforce)" == "Enforcing" ]]; then
    chcon -R -t httpd_sys_rw_content_t "${INSTALL_DIR}/uploads" 2>/dev/null || true
  fi
}

run_db_bootstrap() {
  log "Loading schema, migrations, and seed data…"
  php "${INSTALL_DIR}/deploy/ec2/setup-cli.php"
}

restart_web() {
  systemctl restart "${APACHE_SERVICE}"
}

public_url() {
  local ip=""
  if curl -fsS --connect-timeout 1 http://169.254.169.254/latest/meta-data/public-ipv4 >/dev/null 2>&1; then
    ip="$(curl -fsS --connect-timeout 2 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)"
  fi
  if [[ -z "${ip}" ]]; then
    ip="$(curl -fsS --connect-timeout 2 ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  if [[ -n "${ip}" ]]; then
    echo "http://${ip}${BASE_URL}/"
  else
    echo "http://YOUR-SERVER-IP${BASE_URL}/"
  fi
}

main() {
  local os
  os="$(detect_os)"
  install_packages "${os}"
  wait_for_mariadb
  deploy_app
  setup_database
  write_config_local
  fix_permissions
  run_db_bootstrap
  restart_web

  local url
  url="$(public_url)"

  echo ""
  echo "=============================================="
  echo "  YourLMS installed successfully"
  echo "=============================================="
  echo "  URL:      ${url}"
  echo "  Login:    ${url}login.php"
  echo "  Path:     ${INSTALL_DIR}"
  echo "  Database: ${DB_NAME} (user: ${DB_USER})"
  echo ""
  echo "  Demo login:"
  echo "    instructor@yourlms.test / password123"
  echo ""
  echo "  Optional: open setup.php in browser to re-run DB steps."
  echo "  Security group: allow inbound TCP port 80."
  echo "=============================================="
}

main "$@"