#!/usr/bin/env bash
# Install YourLMS as Debian (Apache+PHP) + MariaDB under the user's home directory.
# Requires: Docker and Docker Compose v2
#
# Usage (from the YourLMS repo):
#   bash deploy/debian-home/setup.sh
#
# Optional:
#   YOURLMS_HOME=~/apps/yourlms YOURLMS_PORT=9080 bash deploy/debian-home/setup.sh

set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is required. Install Docker Desktop or docker.io, then re-run." >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required (docker compose)." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INSTALL_DIR="${YOURLMS_HOME:-${HOME}/yourlms-debian}"
PORT="${YOURLMS_PORT:-8080}"

mkdir -p "${INSTALL_DIR}/data/mysql"

if [[ ! -f "${INSTALL_DIR}/.env" ]]; then
  DB_ROOT_PASS="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)"
  DB_APP_PASS="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p | tail -c 33)"
  cat > "${INSTALL_DIR}/.env" <<EOF
APP_ROOT=${APP_ROOT}
INSTALL_DIR=${INSTALL_DIR}
YOURLMS_PORT=${PORT}
MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
MYSQL_PASSWORD=${DB_APP_PASS}
EOF
  chmod 600 "${INSTALL_DIR}/.env"
  echo "Created ${INSTALL_DIR}/.env with generated database passwords."
else
  # shellcheck disable=SC1090
  source "${INSTALL_DIR}/.env"
  DB_APP_PASS="${MYSQL_PASSWORD}"
  echo "Using existing ${INSTALL_DIR}/.env"
fi

# shellcheck disable=SC1090
source "${INSTALL_DIR}/.env"

cat > "${INSTALL_DIR}/config.local.php" <<EOF
<?php
declare(strict_types=1);

// Auto-generated by deploy/debian-home/setup.sh — Docker home install
return [
    'base_url' => '',
    'db' => [
        'host' => 'db',
        'port' => 3306,
        'name' => 'yourlms',
        'user' => 'yourlms',
        'pass' => '${DB_APP_PASS}',
        'charset' => 'utf8mb4',
    ],
];
EOF
chmod 600 "${INSTALL_DIR}/config.local.php"

cp "${SCRIPT_DIR}/docker-compose.yml" "${INSTALL_DIR}/docker-compose.yml"

cat > "${INSTALL_DIR}/yourlms" <<'WRAPPER'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}"
cmd="${1:-help}"
case "${cmd}" in
  start)
    docker compose --env-file .env up -d --build
    # shellcheck disable=SC1091
    source .env
    echo ""
    echo "YourLMS is starting. Open: http://localhost:${YOURLMS_PORT:-8080}/"
    echo "Demo login: instructor@yourlms.test / password123"
    ;;
  stop)
    docker compose --env-file .env down
    ;;
  restart)
    docker compose --env-file .env down
    docker compose --env-file .env up -d --build
    ;;
  logs)
    docker compose --env-file .env logs -f "${2:-}"
    ;;
  status)
    docker compose --env-file .env ps
    ;;
  url)
    # shellcheck disable=SC1091
    source .env 2>/dev/null || true
    echo "http://localhost:${YOURLMS_PORT:-8080}/"
    ;;
  uninstall)
    read -r -p "Stop containers and remove ${DIR}? [y/N] " ans
    if [[ "${ans}" == "y" || "${ans}" == "Y" ]]; then
      docker compose --env-file .env down -v 2>/dev/null || true
      rm -rf "${DIR}"
      echo "Removed ${DIR}"
    fi
    ;;
  *)
    echo "Usage: yourlms {start|stop|restart|logs|status|url|uninstall}"
    ;;
esac
WRAPPER
chmod +x "${INSTALL_DIR}/yourlms"

echo ""
echo "=== YourLMS home install ready ==="
echo "Install directory: ${INSTALL_DIR}"
echo "App source:        ${APP_ROOT}"
echo ""
echo "Start the stack:"
echo "  ${INSTALL_DIR}/yourlms start"
echo ""
echo "Then open:"
echo "  http://localhost:${PORT}/"
echo ""
echo "Manage:"
echo "  ${INSTALL_DIR}/yourlms stop | logs | status | url"
echo ""

read -r -p "Start YourLMS now? [Y/n] " start_now
if [[ -z "${start_now}" || "${start_now}" =~ ^[Yy]$ ]]; then
  "${INSTALL_DIR}/yourlms" start
fi